### ISSUE TITLE
建议分个类

### ISSUE THREAD

**Issue by byc233518** [cbamls/AI_Tutorial#2]
内容有些太丰富

**Comment by cbamls** [comment]
哈～ ，一直有这想法，不过一直没有想清楚怎么分类比较合适。目前线上只是给资源打了标签。感兴趣的话，我们可以一块讨论下，搞一搞

**Comment by kquark** [comment]
有些内容的确不太好分类，可能一篇文章同时属于多个类，打标签方式会更好一些。

检索已经改变了我们获取信息的习惯，怎样使得检索更加智能，这个更加能提高获取信息的效率。

可能用户检索的词语和表达和知识库文章的表达不太一样，期望是都能返回密切相关的文章，您分享的文章有很多这方面的研究。

例如：
1. 知识库文章中用到是“搜索”这个词，而用户用“检索”这个词。
2. 知识库文章中用“基于 BERT 的 ASR 纠错”这个表述，而用户用“用预训练模型来纠正语音识别错误的方法”。

**Comment by cbamls** [comment]
嗯呢，Query的理解毕竟是很重要的模块
