### ISSUE TITLE
AI实时周报挂了

### ISSUE THREAD

**Issue by Xiangtai-Chen** [cbamls/AI_Tutorial#9]
大佬，网站上的AI实时周报没了。
github上滚动周报也没了。
麻烦看看
<img width="1336" alt="image" src="https://github.com/cbamls/AI_Tutorial/assets/74897447/4527e984-71e5-476a-aae3-44da7ddb5f36">

**Comment by cbamls** [comment]
感谢提醒～实时周报修复了。也欢迎举荐一些知名博主
